{{- if and .Values.environment.create (not .Values.useVaultInjection) -}}
{{- if .Values.environment.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkeyenterprise.fullname" . }}
  labels:
    {{- include "portkeyenterprise.labels" . | nindent 4 }}
data:    
{{- range $key, $val := .Values.environment.data }}
  {{ $key }}: {{- if $val }} {{ $val | b64enc }} {{- else }} "" {{- end }}
{{- end -}}
{{- else -}}  
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portkeyenterprise.fullname" . }}
  labels:
    {{- include "portkeyenterprise.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.environment.data }}
  {{ $key }}: {{ $val }}
{{- end -}}
{{- end -}}
{{- end -}}