apiVersion: v1
kind: Service
metadata:
  name: {{ include "portkeyenterprise.fullname" . }}
  labels:
    {{- include "portkeyenterprise.labels" . | nindent 4 }}
    {{- with .Values.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8787
      protocol: TCP
      name: "portkey"
  selector:
    {{- include "portkeyenterprise.selectorLabels" . | nindent 4 }}
