{{- if eq .Values.environment.data.CACHE_STORE "redis" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - image: "{{ .Values.images.redisImage.repository }}:{{ .Values.images.redisImage.tag }}"
          name: redis
          resources:
            {{- toYaml .Values.redisResources | nindent 12 }}
      restartPolicy: Always
{{- end -}}